apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: https-map-crt
spec:
  secretName: https-map-crt
  dnsNames:
  - map-dev.chronas.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - map-dev.chronas.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer          