apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: https-map
spec:
  secretName: https-map
  dnsNames:
  - chronas.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - chronas.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer          